// app/portal/api/events/[id]/registrations/route.ts
export const runtime = 'nodejs'

import { NextResponse } from 'next/server'
import { getPrisma } from '@/app/lib/safePrisma'
import { devStore } from '@/app/lib/devStore'

// Shape we return to the client
type Row = {
  id: string
  eventId: string
  userId: string
  createdAt: string | null
  user?: { id: string; name?: string | null; email?: string | null } | null
}

// Shape we read from DB/devStore (snake_case columns).
// NOTE: `id` is optional here so devStore.create can omit it and let devStore generate one.
type RowDb = {
  id?: string
  event_id: string
  user_id: string
  created_at: string | Date | null
  user?: { id: string; name?: string | null; email?: string | null } | null
}

function asIso(d: string | Date | null): string | null {
  if (!d) return null
  return d instanceof Date ? d.toISOString() : d
}

export async function GET(_req: Request, context: any) {
  try {
    const { id } = context.params as { id: string }
    const prisma = await getPrisma()

    if (prisma) {
      const rows = (await prisma.registrations.findMany({
        where: { event_id: id },
        orderBy: { created_at: 'desc' },
        // include: { user: true }, // enable if/when you add the relation in Prisma
      })) as unknown as RowDb[]

      const out: Row[] = rows.map((r) => ({
        id: r.id!, // Prisma rows always have id
        eventId: r.event_id,
        userId: r.user_id,
        createdAt: asIso(r.created_at),
        user: r.user ?? null,
      }))

      return NextResponse.json(out)
    }

    // devStore fallback
    const rows = devStore
      .getAll<RowDb>('registrations')
      .filter((r) => r.event_id === id)
      .sort((a, b) => (asIso(b.created_at) ?? '').localeCompare(asIso(a.created_at) ?? ''))

    const out: Row[] = rows.map((r) => ({
      id: r.id!, // devStore sets it when created
      eventId: r.event_id,
      userId: r.user_id,
      createdAt: asIso(r.created_at),
      user: r.user ?? null,
    }))

    return NextResponse.json(out)
  } catch (e: any) {
    console.error('GET /portal/api/events/[id]/registrations error:', e)
    return NextResponse.json({ error: 'Server error' }, { status: 500 })
  }
}

export async function POST(req: Request, context: any) {
  try {
    const { id } = context.params as { id: string }
    const body = await req.json().catch(() => ({}))
    const userId = String(body?.userId ?? '').trim()
    if (!userId) return NextResponse.json({ error: 'userId required' }, { status: 400 })

    const prisma = await getPrisma()
    if (prisma) {
      const created = (await prisma.registrations.create({
        data: {
          event_id: id,
          user_id: userId,
        },
      })) as unknown as RowDb

      const out: Row = {
        id: created.id!, // Prisma returns id
        eventId: created.event_id,
        userId: created.user_id,
        createdAt: asIso(created.created_at),
        user: null,
      }
      return NextResponse.json(out, { status: 201 })
    }

    // devStore fallback — no id provided, devStore will generate one.
    const created = devStore.upsert<RowDb>('registrations', {
      event_id: id,
      user_id: userId,
      created_at: new Date(),
    })

    const out: Row = {
      id: created.id!, // generated by devStore
      eventId: created.event_id,
      userId: created.user_id,
      createdAt: asIso(created.created_at),
      user: null,
    }
    return NextResponse.json(out, { status: 201 })
  } catch (e: any) {
    console.error('POST /portal/api/events/[id]/registrations error:', e)
    return NextResponse.json({ error: e?.message ?? 'Invalid payload' }, { status: 400 })
  }
}